insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (1, 'Major', 'Sloth, hoffman''s', 'Choloepus hoffmani', 13, '7/5/2024', '7/2/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (2, 'Borden', 'Great kiskadee', 'Pitangus sulphuratus', 9, '10/16/2021', '7/14/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (3, 'Lorilyn', 'Beaver, american', 'Castor canadensis', 7, '6/8/2022', '7/4/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (4, 'Gusta', 'Common pheasant', 'Phasianus colchicus', 3, '9/6/2022', '7/18/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (5, 'Claudian', 'Woodcock, american', 'Scolopax minor', 13, '9/5/2023', '7/7/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (6, 'Cyrillus', 'Lizard, frilled', 'Chlamydosaurus kingii', 7, '11/14/2021', '7/21/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (7, 'Christean', 'Eastern cottontail rabbit', 'Sylvilagus floridanus', 14, '5/17/2022', '7/27/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (8, 'Leandra', 'Tamandua, southern', 'Tamandua tetradactyla', 3, '5/30/2023', '7/9/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (9, 'Guss', 'Hawk, ferruginous', 'Buteo regalis', 12, '9/2/2021', '7/28/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (10, 'Ginnie', 'Jackal, indian', 'Canis aureus', 15, '4/1/2023', '7/17/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (11, 'Amara', 'Kafue flats lechwe', 'Kobus leche robertsi', 6, '2/16/2023', '7/3/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (12, 'Nickola', 'Tortoise, galapagos', 'Geochelone elephantopus', 8, '7/18/2021', '7/21/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (13, 'Hyacinthe', 'Macaw, red and blue', 'Ara chloroptera', 4, '10/10/2023', '7/15/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (14, 'Jena', 'Cat, african wild', 'Felis silvestris lybica', 5, '9/30/2022', '7/21/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (15, 'Spencer', 'Yellow-throated sandgrouse', 'Pterocles gutturalis', 6, '2/26/2024', '7/13/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (16, 'Dwight', 'Least chipmunk', 'Eutamias minimus', 12, '3/5/2022', '7/27/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (17, 'Waylon', 'Lemming, arctic', 'Dicrostonyx groenlandicus', 4, '10/26/2023', '7/6/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (18, 'Nissie', 'Red howler monkey', 'Alouatta seniculus', 2, '10/25/2023', '7/12/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (19, 'Cris', 'Orca', 'Orcinus orca', 9, '5/21/2023', '7/7/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (20, 'Khalil', 'Greater flamingo', 'Phoenicopterus ruber', 6, '4/3/2022', '7/28/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (21, 'Piotr', 'Euro wallaby', 'Macropus robustus', 4, '5/16/2022', '7/7/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (22, 'Carlynn', 'Bulbul, african red-eyed', 'Pycnonotus nigricans', 5, '9/14/2022', '7/11/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (23, 'Bev', 'Eagle, long-crested hawk', 'Lophoaetus occipitalis', 10, '7/12/2021', '7/1/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (24, 'Tera', 'Badger, eurasian', 'Meles meles', 2, '9/30/2021', '7/15/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (25, 'Georgette', 'Southern brown bandicoot', 'Isoodon obesulus', 7, '6/20/2022', '7/29/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (26, 'Yehudi', 'Wallaroo, common', 'Macropus robustus', 8, '12/14/2023', '7/9/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (27, 'Carrol', 'Ostrich', 'Struthio camelus', 8, '8/2/2023', '7/15/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (28, 'Averil', 'Curve-billed thrasher', 'Toxostoma curvirostre', 9, '10/6/2022', '7/24/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (29, 'Amaleta', 'Brown and yellow marshbird', 'Pseudoleistes virescens', 10, '2/19/2022', '7/11/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (30, 'Rycca', 'Skimmer, four-spotted', 'Libellula quadrimaculata', 1, '6/27/2022', '7/17/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (31, 'Adah', 'Polar bear', 'Ursus maritimus', 15, '6/19/2023', '7/2/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (32, 'Lela', 'Fox, pampa gray', 'Pseudalopex gymnocercus', 5, '6/6/2024', '7/1/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (33, 'Sloan', 'Ibex', 'Capra ibex', 2, '3/7/2024', '7/28/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (34, 'Anna-diane', 'Giraffe', 'Giraffe camelopardalis', 15, '4/14/2023', '7/10/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (35, 'Mickey', 'Canada goose', 'Branta canadensis', 1, '2/20/2024', '7/21/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (36, 'Gwennie', 'Genet, small-spotted', 'Genetta genetta', 12, '9/25/2021', '7/9/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (37, 'Leanna', 'Cormorant, king', 'Phalacrocorax albiventer', 15, '5/7/2023', '7/21/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (38, 'Odo', 'Goose, andean', 'Chloephaga melanoptera', 2, '5/21/2024', '7/14/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (39, 'Jourdain', 'Pied butcher bird', 'Cracticus nigroagularis', 12, '12/22/2021', '7/24/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (40, 'Lizabeth', 'Land iguana', 'Conolophus subcristatus', 7, '1/8/2022', '7/17/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (41, 'Cole', 'Eagle, long-crested hawk', 'Lophoaetus occipitalis', 15, '12/2/2021', '7/19/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (42, 'Roman', 'Fox, asian red', 'Vulpes vulpes', 3, '4/9/2023', '7/1/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (43, 'Tamera', 'Blue crane', 'Anthropoides paradisea', 10, '7/22/2024', '7/7/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (44, 'Sollie', 'Woodrat (unidentified)', 'Neotoma sp.', 6, '8/5/2023', '7/1/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (45, 'Katrine', 'Eagle, white-bellied sea', 'Haliaetus leucogaster', 5, '8/4/2022', '7/29/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (46, 'Kylie', 'Langur, common', 'Semnopithecus entellus', 13, '8/4/2023', '7/1/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (47, 'Kanya', 'Weaver, lesser masked', 'Ploceus intermedius', 3, '4/11/2023', '7/19/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (48, 'Sheilakathryn', 'Bat, asian false vampire', 'Megaderma spasma', 7, '12/17/2022', '7/16/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (49, 'Honey', 'White-lipped peccary', 'Tayassu pecari', 9, '9/18/2023', '7/17/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (50, 'Sarah', 'European stork', 'Ciconia ciconia', 2, '8/13/2021', '7/24/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (51, 'Pebrook', 'Long-necked turtle', 'Chelodina longicollis', 5, '5/16/2021', '7/17/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (52, 'Norrie', 'Tropical buckeye butterfly', 'Junonia genoveua', 6, '7/7/2021', '7/18/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (53, 'Patrizia', 'Duck, blue', 'Hymenolaimus malacorhynchus', 12, '11/1/2021', '7/15/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (54, 'Hebert', 'Peccary, white-lipped', 'Tayassu pecari', 11, '3/5/2022', '7/7/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (55, 'Bunnie', 'Robin, kalahari scrub', 'Certotrichas paena', 11, '7/5/2021', '7/22/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (56, 'Aura', 'Ring-tailed possum', 'Pseudocheirus peregrinus', 1, '5/26/2024', '7/9/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (57, 'Ken', 'Quoll, eastern', 'Dasyurus viverrinus', 13, '5/24/2021', '7/19/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (58, 'Erich', 'Water moccasin', 'Agkistrodon piscivorus', 13, '10/15/2023', '7/23/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (59, 'Kennedy', 'Wolf, mexican', 'Canis lupus baileyi', 14, '7/15/2023', '7/24/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (60, 'Deeann', 'Gull, lava', 'Larus fuliginosus', 5, '11/15/2021', '7/4/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (61, 'Annalee', 'Stork, woolly-necked', 'Ciconia episcopus', 9, '3/5/2022', '7/12/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (62, 'Arlyne', 'Long-billed cockatoo', 'Cacatua tenuirostris', 8, '5/21/2023', '7/12/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (63, 'Charin', 'Indian giant squirrel', 'Ratufa indica', 4, '8/21/2022', '7/1/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (64, 'Mariam', 'Pronghorn', 'Antilocapra americana', 5, '3/3/2022', '7/23/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (65, 'Brooke', 'Marten, american', 'Martes americana', 8, '6/24/2021', '7/18/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (66, 'Kare', 'Frilled lizard', 'Chlamydosaurus kingii', 14, '1/8/2023', '7/30/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (67, 'Petey', 'Wolf, mexican', 'Canis lupus baileyi', 11, '11/1/2022', '7/23/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (68, 'Camille', 'Common zebra', 'Equus burchelli', 14, '7/18/2024', '7/21/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (69, 'Kennith', 'Wallaroo, common', 'Macropus robustus', 15, '3/11/2023', '7/18/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (70, 'Eberhard', 'Laughing dove', 'Streptopelia senegalensis', 5, '12/28/2023', '7/21/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (71, 'Lorie', 'Red-billed hornbill', 'Tockus erythrorhyncus', 7, '12/15/2021', '7/14/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (72, 'Crystie', 'Greater rhea', 'Rhea americana', 13, '6/23/2024', '7/9/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (73, 'Karlik', 'Arctic hare', 'Lepus arcticus', 13, '2/20/2022', '7/7/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (74, 'Powell', 'Woodchuck', 'Marmota monax', 3, '6/23/2022', '7/16/2024');
insert into animals (animal_id, nickname, common_name, scientific_name, age, date_arrived, last_checkup) values (75, 'Ora', 'Turkey vulture', 'Cathartes aura', 11, '1/20/2022', '7/1/2024');
